apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nnku7g6qj-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nnku7g6qj-go 
  name: nnku7g6qj-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nnku7g6qj-go 
